homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 139
  unit_system: imperial
  time_zone: !secret time_zone
  customize: !include customize.yaml

frontend: 

http:
  # Uncomment this to add a password (recommended!) api_password: 
  # PASSWORD Uncomment this if you are using SSL or running in Docker 
  # etc base_url: example.duckdns.org:8123

updater:

# Discover some devices automatically
discovery: 

device_tracker:
  - platform: unifi
    username: !secret unifi_user
    password: !secret unifi_pw
    host: !secret unifi_host
    verify_ssl: False 

nest:
  client_id: !secret nest_id
  client_secret: !secret nest_secret 
  binary_sensors:
    monitored_conditions:
  sensors:
    monitored_conditions:
      - 'humidity'

#media_player: !include media_player.yaml

# Allows you to issue voice commands from the frontend in enabled 
# browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Weather Prediction
sensor: !include sensor.yaml
      
binary_sensor:
  - platform: iss
  
# Text to speech
tts:
  platform: google

#hello_state:
  
camera:
  name: ISS
  platform: generic
  still_image_url: https://maps.googleapis.com/maps/api/staticmap?center={{ states.binary_sensor.iss.attributes.lat }},{{ states.binary_sensor.iss.attributes.long }}&zoom=5&size=500x500&maptype=roadmap&markers=color:blue%7Clabel:P%7C{{ states.binary_sensor.iss.attributes.lat }},{{ states.binary_sensor.iss.attributes.long }}
  limit_refetch_to_url_change: true
  
group: !include group.yaml
