<<<<<<< HEAD
media_player:
  - platform: monoprice
    port: /dev/ttyUSB0
    zones:
      11:
        name: Kitchen Speakers
      12:
        name: Patio Speakers
      13:
        name: Office Speakers
      14:
        name: Gym Speakers
    sources:
      5:
        name: TV         
      6:
        name: Chromecast
- platform: cast
  host: 192.168.2.42
- platform: plex
  host: 192.168.2.75
=======
# Powered sub is attached to this zone's preamp out
- platform: mpr_6zhmaut
  name: Kitchen Speakers
  host: !secret mpr_api_ip
  port: !secret mpr_api_port
  zone: 11
- platform: mpr_6zhmaut
  name: Patio Speakers
  host: !secret mpr_api_ip
  port: !secret mpr_api_port
  zone: 12
- platform: mpr_6zhmaut
  name: Office Speakers
  host: !secret mpr_api_ip
  port: !secret mpr_api_port
  zone: 13
- platform: mpr_6zhmaut
  name: Gym Speakers
  host: !secret mpr_api_ip
  port: !secret mpr_api_port
  zone: 14
- platform: cast
- platform: plex
>>>>>>> 562fbb074d8b53b5b2d3765603171d62292b838d
  
