media_player:
  - platform: monoprice
    port: /dev/ttyUSB0
    zones:
      11:
        name: Kitchen Speakers
      12:
        name: Patio Speakers
      13:
        name: Office Speakers
      14:
        name: Gym Speakers
    sources:
      5:
        name: TV         
      6:
        name: Chromecast
- platform: cast
  host: 192.168.2.42
- platform: plex
  host: 192.168.2.75
  
