- platform: pi_hole
  host: !secret pi_hole_host
- platform: moon
- platform: speedtest
  monitored_conditions:
    - ping
    - download
    - upload
  hour:
    - 7
    - 12
    - 18
- platform: wunderground
  api_key: !secret wg_api
  monitored_conditions:
    - dewpoint_f
    - feelslike_f
    - location
    - observation_time
    - precip_today_in
    - pressure_in
    - pressure_trend
    - relative_humidity
    - temperature_string
    - weather
    - wind_string
- platform: etherscan
  address: !secret ether
